'use client';

import { createConfig, fallback, http, cookieStorage, createStorage, type CreateConnectorFn } from 'wagmi';
// Per-connector subpath imports, NOT the '@wagmi/connectors' barrel.
//
// The barrel re-exports every connector, which drags in `tempoWallet` ->
// `@wagmi/core/tempo` -> `viem/tempo/zones`, a module no published viem
// exports yet, and the build dies on an unresolvable import from a connector
// this app never registers. It also pulls `baseAccount` -> @base-org/account
// -> @coinbase/cdp-sdk -> @x402/*, none of which are installed.
//
// v8 of the package added a subpath export per connector. Importing only the
// five that are actually used keeps both of those subtrees out of the bundle,
// and does so through the package's public API rather than a webpack alias
// that has to be re-tuned every time the dependency tree shifts.
import { injected } from '@wagmi/connectors/injected';
import { metaMask } from '@wagmi/connectors/metaMask';
import { coinbaseWallet } from '@wagmi/connectors/coinbaseWallet';
import { safe } from '@wagmi/connectors/safe';
import { walletConnect } from '@wagmi/connectors/walletConnect';
import { robinhoodTestnet, robinhoodMainnet, isMainnet } from './chains';
import { SITE_URL } from './site-url';

/**
 * WalletConnect project id, from https://dashboard.reown.com.
 *
 * Without it there is no mobile wallet support at all: phone wallets connect
 * over the WalletConnect relay, not through an injected provider. A token site
 * that only supports desktop browser extensions is unreachable for most of its
 * audience, so `walletConnectAvailable` is surfaced to the UI rather than
 * failing quietly.
 */
const wcProjectId = process.env.NEXT_PUBLIC_WC_PROJECT_ID;
export const walletConnectAvailable = Boolean(wcProjectId);

const appName = 'Zorpha';
const appUrl = SITE_URL;

function buildConnectors(): CreateConnectorFn[] {
  const connectors: CreateConnectorFn[] = [
    // Any EIP-1193 browser extension: MetaMask, Rabby, Brave, OKX, Trust,
    // Frame. `shimDisconnect` makes an explicit disconnect stick across
    // reloads instead of silently reconnecting.
    injected({ shimDisconnect: true }),

    // Dedicated MetaMask connector on top of the generic injected one: it adds
    // mobile deep-linking, so tapping "MetaMask" on a phone opens the app
    // rather than doing nothing.
    metaMask({
      dappMetadata: { name: appName, url: appUrl },
    }),

    coinbaseWallet({
      appName,
      // Smart-wallet-first would create a fresh passkey account for people who
      // already hold assets in their Coinbase Wallet extension. `all` offers
      // both and lets them choose.
      //
      // The object form is required from @coinbase/wallet-sdk v4: `preference`
      // used to be a bare string and is now a config object.
      preference: { options: 'all' },
    }),

    // Only connects inside a Safe App iframe, where it auto-connects. Included
    // because Zorpha governance IS a Safe: without this, the multisig that owns
    // the Timelock cannot use its own portal.
    safe({ allowedDomains: [/app\.safe\.global$/] }),
  ];

  if (wcProjectId) {
    connectors.push(
      walletConnect({
        projectId: wcProjectId,
        metadata: {
          name: appName,
          description: 'Verifiable onchain asset management on Robinhood Chain',
          url: appUrl,
          // `/apple-icon` is a real 180x180 PNG generated by
          // app/apple-icon.tsx. This used to point at `/icon.png`, which was
          // never in the repo, so the wallet approval dialog showed a broken
          // image while asking the user to trust the site.
          icons: [`${appUrl}/apple-icon`],
        },
        showQrModal: true,
      }),
    );
  }

  return connectors;
}

/**
 * Every RPC a chain declares, tried in order.
 *
 * The comment here used to claim each chain got a fallback transport. It did
 * not. Both entries were `http(rpcUrls.default.http[0])`, so the second URL
 * `robinhoodMainnet` has carried all along was never contacted, and a portal
 * that looked redundant had exactly one point of failure.
 *
 * That came due on 7 September 2026, when the RPC's edge returned
 * `Access-Control-Allow-Origin: *,*` on some responses. A duplicated header is
 * a value no browser accepts, so the fetch is refused before the app sees it,
 * and every live read on the page went with it.
 *
 * `retryCount` drops from 2 to 1 because the redundancy now lives in the
 * fallback rather than in repetition. Retrying a URL that a browser has
 * already refused to load costs a round trip to learn what the first attempt
 * proved; one retry keeps a genuinely transient blip from failing over, and
 * anything worse moves on quickly.
 *
 * Order is deliberate and `rank` is left off. Ranking probes endpoints in the
 * background to reorder them by latency, which trades a steady trickle of
 * requests for a preference between two nodes that answer identically. The
 * canonical endpoint stays first.
 */
function transportFor(chain: { rpcUrls: { default: { http: readonly string[] } } }) {
  return fallback(
    chain.rpcUrls.default.http.map((url) => http(url, { batch: true, retryCount: 1 })),
  );
}

/**
 * Both chains are registered even though only one is the active target. wagmi
 * derives the `transports` key type from the `chains` tuple, so declaring a
 * single conditionally-selected chain widens the tuple to the union of both ids
 * and then demands a transport for each. Registering both is simpler than
 * casting, and it lets `useSwitchChain` move a user between them.
 *
 * THE ACTIVE CHAIN MUST COME FIRST.
 *
 * `createConfig` seeds `state.chainId` from `chains[0]`, and that is the chain
 * every `useReadContract` without an explicit `chainId` reads against. With
 * testnet hardcoded first, a disconnected visitor to a mainnet build read
 * chain 46630 for any hook that did not name a chain, which is most of the
 * portal.
 *
 * That was invisible for as long as it was paired with a second mistake:
 * `NEXT_PUBLIC_RPC_URL` is the mainnet endpoint on a mainnet build and it was
 * feeding the TESTNET chain object, so those testnet-id reads were sent to the
 * mainnet node and came back with mainnet state. Two faults cancelling out,
 * and fixing either one alone breaks the portal. See lib/chains.ts, which no
 * longer lets the override cross chains.
 *
 * Ordering by the active chain fixes it for every consumer at once, rather
 * than waiting for each hook to remember a `chainId` it should not have to
 * name. The hooks that read a specific chain still pass one.
 */
export const wagmiConfig = createConfig({
  chains: isMainnet
    ? ([robinhoodMainnet, robinhoodTestnet] as const)
    : ([robinhoodTestnet, robinhoodMainnet] as const),
  connectors: buildConnectors(),
  transports: {
    [robinhoodTestnet.id]: transportFor(robinhoodTestnet),
    [robinhoodMainnet.id]: transportFor(robinhoodMainnet),
  },
  // Cookie storage keeps connection state consistent between the server render
  // and hydration, which is what stops the wallet button flashing "Connect" for
  // a frame on every navigation.
  ssr: true,
  storage: createStorage({ storage: cookieStorage }),
});

declare module 'wagmi' {
  interface Register {
    config: typeof wagmiConfig;
  }
}
