#!/usr/bin/env bash
# Emit the SQL that puts the deployed vaults into Supabase's `vaults` table.
#
# The indexer's .env.example says "Vaults are normally discovered from the
# `vaults` table, which the deploy script populates". Nothing populates it. The
# deploy scripts have never written a row, so on a fresh Supabase project the
# table is empty, listVaults() returns [], and every vault page renders its
# empty state. That failure is silent by design -- lib/queries.ts degrades to
# empty rather than throwing, so the marketing site still builds when the
# backend does not exist -- which is right, and also means nothing anywhere
# says why the site shows no vaults.
#
# This reads the chain and prints INSERTs. It does not write, because writing
# needs the service-role key: RLS on `vaults` grants select to anon and nothing
# else, so the anon key in .env.local cannot seed it, and the service-role key
# should not be passed around. Paste the output into the Supabase SQL editor,
# which authenticates as your dashboard session.
#
# Usage:
#   ./script/seed-vaults-sql.sh                 # print
#   ./script/seed-vaults-sql.sh > seed.sql      # save
#
# Read-only: no keystore, no password, no transactions.

set -euo pipefail

if ! command -v cast >/dev/null; then
  [[ -d "$HOME/.foundry/bin" ]] && { PATH="$HOME/.foundry/bin:$PATH"; export PATH; }
fi
command -v cast >/dev/null || { echo "ERROR: cast not found" >&2; exit 1; }
command -v node >/dev/null || { echo "ERROR: node not found" >&2; exit 1; }

RPC="${RH_TESTNET_RPC_URL:-https://rpc.testnet.chain.robinhood.com/rpc}"
CHAIN_ID=46630
WEB_ENV="../../zorpha-web/.env.local"
VAULT_BROADCAST="broadcast/DeployVaultsV1.s.sol/$CHAIN_ID/run-latest.json"

log() { printf '%s\n' "$*" >&2; }   # progress on stderr, SQL on stdout
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

[[ -f "$WEB_ENV" ]] || die "no $WEB_ENV"

env_of() { grep -E "^$1=" "$WEB_ENV" | head -1 | cut -d= -f2-; }
num()    { awk '{print $1}'; }
# A failed call means "this vault type does not have that accessor", which is
# how the type is detected. Never fatal.
try()    { cast call "$@" --rpc-url "$RPC" 2>/dev/null | num || true; }
# Strip the quotes cast puts around a returned string.
str()    { cast call "$@" --rpc-url "$RPC" 2>/dev/null | sed 's/^"//;s/"$//' || true; }
# Single-quote for SQL, or NULL when empty.
q()      { [[ -z "${1:-}" ]] && printf 'NULL' || printf "'%s'" "${1//\'/\'\'}"; }

LAUNCHER=$(env_of NEXT_PUBLIC_VAULT_LAUNCHER_ADDRESS)
EXECUTOR=$(env_of NEXT_PUBLIC_STRATEGY_EXECUTOR_ADDRESS)

# The factory vaults are managed by whoever the executor will accept signatures
# from. There is exactly one such address, so it is the manager for all three.
DEFAULT_MANAGER=$(try "$EXECUTOR" 'authorizedSigner()(address)')
[[ -n "$DEFAULT_MANAGER" ]] || die "could not read authorizedSigner from the executor"
log "executor's authorizedSigner: $DEFAULT_MANAGER"

# --- Collect the vaults ----------------------------------------------------
# Two sources, because they are created two different ways: the three from
# DeployVaultsV1 come out of the factory during the deploy script and appear as
# CREATE2 entries in its broadcast artifact; leader vaults are created later by
# VaultLauncher and are only in its `launches` array.
declare -a ADDRS=() LEADERS=()

if [[ -f "$VAULT_BROADCAST" ]]; then
  while read -r a; do
    [[ -n "$a" ]] && { ADDRS+=("$a"); LEADERS+=(""); }
  done < <(node -e '
    const j = require(process.argv[1]);
    const seen = new Set();
    for (const t of j.transactions || [])
      for (const x of t.additionalContracts || [])
        if (x.address && !seen.has(x.address)) { seen.add(x.address); console.log(x.address); }
  ' "./$VAULT_BROADCAST")
fi
log "${#ADDRS[@]} vault(s) from the deploy broadcast"

if [[ -n "$LAUNCHER" ]]; then
  COUNT=$(try "$LAUNCHER" 'launchCount()(uint256)')
  COUNT=${COUNT:-0}
  for ((i = 0; i < COUNT; i++)); do
    rec=$(cast call "$LAUNCHER" \
      'launches(uint256)(address,address,address,address,address,uint256,uint64,bool,bool)' \
      "$i" --rpc-url "$RPC" 2>/dev/null || true)
    [[ -z "$rec" ]] && continue
    ADDRS+=("$(echo "$rec" | sed -n '1p' | num)")
    LEADERS+=("$(echo "$rec" | sed -n '4p' | num)")
  done
  log "$COUNT leader-launched vault(s)"
fi

[[ ${#ADDRS[@]} -gt 0 ]] || die "found no vaults"

# --- Emit ------------------------------------------------------------------
printf -- '-- Zorpha vault seed, generated %s from chain %s\n' "$(date -u '+%Y-%m-%d %H:%M UTC')" "$CHAIN_ID"
printf -- '-- Generated by contracts/script/seed-vaults-sql.sh. Do not hand-edit;\n'
printf -- '-- re-run it instead, so the rows keep matching what is actually deployed.\n'
printf -- '--\n'
printf -- '-- `strategy` is the one field with no on-chain source. It is prose for the\n'
printf -- '-- portal, so the defaults below are placeholders -- edit them before this\n'
printf -- '-- reaches anyone who is not you.\n\n'

# Drill and scratch vaults are real deployments and would otherwise be listed
# alongside the ones people are meant to use. Comma-separated, case-insensitive.
EXCLUDE=",$(printf '%s' "${EXCLUDE_VAULTS:-}" | tr 'A-Z' 'a-z' | tr -d ' '),"

for i in "${!ADDRS[@]}"; do
  V="${ADDRS[$i]}"
  LEADER="${LEADERS[$i]}"

  if [[ "$EXCLUDE" != ",," && "$EXCLUDE" == *",$(printf '%s' "$V" | tr 'A-Z' 'a-z'),"* ]]; then
    log "  excluded $V"
    continue
  fi

  NAME=$(str "$V" 'name()(string)')
  [[ -n "$NAME" ]] || { log "skipping $V: no name(), not a vault"; continue; }
  SYMBOL=$(str "$V" 'symbol()(string)')
  ASSET=$(try "$V" 'asset()(address)')

  # Type by which accessor answers. cashAsset is only on the spot vault,
  # baseAsset only on the rotation vault, firstLossEscrow only on the yield one.
  CASH=$(try "$V" 'cashAsset()(address)')
  BASE=$(try "$V" 'baseAsset()(address)')
  ESC=$(try "$V" 'firstLossEscrow()(address)')

  if   [[ -n "$CASH" ]]; then TYPE=spot;     ORACLE=$(try "$V" 'oracle()(address)')
  elif [[ -n "$BASE" ]]; then TYPE=rotation; ORACLE=$(try "$V" 'oracles(uint256)(address)' 0)
  else                        TYPE=yield;    ORACLE=""
  fi

  case "$TYPE" in
    spot)     STRATEGY="Long or flat a single equity, on a signed oracle-checked rebalance." ;;
    rotation) STRATEGY="Rotates between approved real-world assets on a signed mandate." ;;
    yield)    STRATEGY="Allocates to an approved ERC-4626 venue." ;;
  esac

  MANAGER="$DEFAULT_MANAGER"
  if [[ -n "$LEADER" ]]; then
    MANAGER="$LEADER"
    STRATEGY="$STRATEGY Leader-launched, with first-loss capital posted behind depositors."
  fi

  log "  $TYPE  $V  $SYMBOL"

  # ON CONFLICT so a re-run is a refresh rather than a duplicate-key error.
  # deployed_at is deliberately left to the column default on insert and
  # untouched on update: it orders the portal's list, and clobbering it on
  # every re-run would reshuffle the page for no reason.
  cat <<SQL
insert into public.vaults
  (address, vault_type, name, symbol, asset, cash, base_asset, oracle, strategy, manager_address)
values
  ($(q "$V"), $(q "$TYPE"), $(q "$NAME"), $(q "$SYMBOL"), $(q "$ASSET"),
   $(q "$CASH"), $(q "$BASE"), $(q "$ORACLE"), $(q "$STRATEGY"), $(q "$MANAGER"))
on conflict (address) do update set
  vault_type      = excluded.vault_type,
  name            = excluded.name,
  symbol          = excluded.symbol,
  asset           = excluded.asset,
  cash            = excluded.cash,
  base_asset      = excluded.base_asset,
  oracle          = excluded.oracle,
  strategy        = excluded.strategy,
  manager_address = excluded.manager_address;

SQL
done

log ""
log "Paste the output into the Supabase SQL editor (it needs write access;"
log "the anon key in .env.local is select-only on this table)."
